version: '3.7'

services:
  api:
    build: .
    entrypoint: bash /fyle-qbo-api/run.sh
    restart: always
    volumes:
    - ./:/fyle-qbo-api
    ports:
    - 8000:8000
    depends_on:
    - db

  qcluster:
    build: .
    entrypoint: bash start_qcluster.sh
    restart: always
    volumes:
    - ./:/code
    depends_on:
    - db
    - redis

  db:
    image: "postgres:latest"
    ports:
    - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data/

  redis:
    image: "redis:alpine"
    command: [sh, -c, "rm -f /data/dump.rdb && redis-server --save ''"]


volumes:
  postgres_data: